mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false
    cache-enabled: true
  type-aliases-package: com.ecjtu.kongtao.bean
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://47.106.251.235:3306/ssm_hotel?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
      driverClassName: com.mysql.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maximum-pool-size: 30
        minimum-idle: 10
        initialization-fail-timeout: 10000
        connection-timeout: 10000
logging:
  level:
      com.ecjtu.kongtao: debug