spring:
  thymeleaf:
      cache: false
      encoding: UTF-8
      mode: HTML5
  profiles:
    active: dao
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: 10MB
server:
  port: 8081